UCLA scl 1.0
NumRows : 20

CoreRow Horizontal
  Coordinate    : 0
  Height        : 10
  Sitewidth     : 1
  Sitespacing   : 1
  Siteorient    : N
  Sitesymmetry  : Y
  SubrowOrigin  : 0  NumSites : 400
End
CoreRow Horizontal
  Coordinate    : 10
  Height        : 10
  Sitewidth     : 1
  Sitespacing   : 1
  Siteorient    : N
  Sitesymmetry  : Y
  SubrowOrigin  : 0  NumSites : 400
End
CoreRow Horizontal
  Coordinate    : 20
  Height        : 10
  Sitewidth     : 1
  Sitespacing   : 1
  Siteorient    : N
  Sitesymmetry  : Y
  SubrowOrigin  : 0  NumSites : 400
End
CoreRow Horizontal
  Coordinate    : 30
  Height        : 10
  Sitewidth     : 1
  Sitespacing   : 1
  Siteorient    : N
  Sitesymmetry  : Y
  SubrowOrigin  : 0  NumSites : 400
End
CoreRow Horizontal
  Coordinate    : 40
  Height        : 10
  Sitewidth     : 1
  Sitespacing   : 1
  Siteorient    : N
  Sitesymmetry  : Y
  SubrowOrigin  : 0  NumSites : 400
End
CoreRow Horizontal
  Coordinate    : 50
  Height        : 10
  Sitewidth     : 1
  Sitespacing   : 1
  Siteorient    : N
  Sitesymmetry  : Y
  SubrowOrigin  : 0  NumSites : 400
End
CoreRow Horizontal
  Coordinate    : 60
  Height        : 10
  Sitewidth     : 1
  Sitespacing   : 1
  Siteorient    : N
  Sitesymmetry  : Y
  SubrowOrigin  : 0  NumSites : 400
End
CoreRow Horizontal
  Coordinate    : 70
  Height        : 10
  Sitewidth     : 1
  Sitespacing   : 1
  Siteorient    : N
  Sitesymmetry  : Y
  SubrowOrigin  : 0  NumSites : 400
End
CoreRow Horizontal
  Coordinate    : 80
  Height        : 10
  Sitewidth     : 1
  Sitespacing   : 1
  Siteorient    : N
  Sitesymmetry  : Y
  SubrowOrigin  : 0  NumSites : 400
End
CoreRow Horizontal
  Coordinate    : 90
  Height        : 10
  Sitewidth     : 1
  Sitespacing   : 1
  Siteorient    : N
  Sitesymmetry  : Y
  SubrowOrigin  : 0  NumSites : 400
End
CoreRow Horizontal
  Coordinate    : 100
  Height        : 10
  Sitewidth     : 1
  Sitespacing   : 1
  Siteorient    : N
  Sitesymmetry  : Y
  SubrowOrigin  : 0  NumSites : 400
End
CoreRow Horizontal
  Coordinate    : 110
  Height        : 10
  Sitewidth     : 1
  Sitespacing   : 1
  Siteorient    : N
  Sitesymmetry  : Y
  SubrowOrigin  : 0  NumSites : 400
End
CoreRow Horizontal
  Coordinate    : 120
  Height        : 10
  Sitewidth     : 1
  Sitespacing   : 1
  Siteorient    : N
  Sitesymmetry  : Y
  SubrowOrigin  : 0  NumSites : 400
End
CoreRow Horizontal
  Coordinate    : 130
  Height        : 10
  Sitewidth     : 1
  Sitespacing   : 1
  Siteorient    : N
  Sitesymmetry  : Y
  SubrowOrigin  : 0  NumSites : 400
End
CoreRow Horizontal
  Coordinate    : 140
  Height        : 10
  Sitewidth     : 1
  Sitespacing   : 1
  Siteorient    : N
  Sitesymmetry  : Y
  SubrowOrigin  : 0  NumSites : 400
End
CoreRow Horizontal
  Coordinate    : 150
  Height        : 10
  Sitewidth     : 1
  Sitespacing   : 1
  Siteorient    : N
  Sitesymmetry  : Y
  SubrowOrigin  : 0  NumSites : 400
End
CoreRow Horizontal
  Coordinate    : 160
  Height        : 10
  Sitewidth     : 1
  Sitespacing   : 1
  Siteorient    : N
  Sitesymmetry  : Y
  SubrowOrigin  : 0  NumSites : 400
End
CoreRow Horizontal
  Coordinate    : 170
  Height        : 10
  Sitewidth     : 1
  Sitespacing   : 1
  Siteorient    : N
  Sitesymmetry  : Y
  SubrowOrigin  : 0  NumSites : 400
End
CoreRow Horizontal
  Coordinate    : 180
  Height        : 10
  Sitewidth     : 1
  Sitespacing   : 1
  Siteorient    : N
  Sitesymmetry  : Y
  SubrowOrigin  : 0  NumSites : 400
End
CoreRow Horizontal
  Coordinate    : 190
  Height        : 10
  Sitewidth     : 1
  Sitespacing   : 1
  Siteorient    : N
  Sitesymmetry  : Y
  SubrowOrigin  : 0  NumSites : 400
End
